{
  "formatVersion": "1.1",
  "component": {
    "group": "me.shedaniel",
    "module": "architectury-plugin",
    "version": "3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "architectury-plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin-3.4-SNAPSHOT.jar",
          "size": 120168,
          "sha512": "df1c13e6dd69be45681bdc92fd50435b136707489e8e22bb567c801f027ab091186557d6d7f90bcec58119c072204e28df64c1e915921978f071e715208f38e7",
          "sha256": "826a582fbc30ee5440a75f8094290a3bafb0a18454cf2018a5c7e8591943de0f",
          "sha1": "d462ee971707e439427d462db54873f02873351f",
          "md5": "007b06b233ae538737188de0da5c55c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-transformer",
          "version": {
            "requires": "5.2.9999"
          }
        },
        {
          "group": "dev.architectury",
          "module": "tiny-remapper",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "architectury-plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin-3.4-SNAPSHOT.jar",
          "size": 120168,
          "sha512": "df1c13e6dd69be45681bdc92fd50435b136707489e8e22bb567c801f027ab091186557d6d7f90bcec58119c072204e28df64c1e915921978f071e715208f38e7",
          "sha256": "826a582fbc30ee5440a75f8094290a3bafb0a18454cf2018a5c7e8591943de0f",
          "sha1": "d462ee971707e439427d462db54873f02873351f",
          "md5": "007b06b233ae538737188de0da5c55c6"
        }
      ]
    }
  ]
}
