{
  "formatVersion": "1.1",
  "component": {
    "group": "me.shedaniel",
    "module": "architectury-plugin",
    "version": "3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "architectury-plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin-3.4-SNAPSHOT.jar",
          "size": 121817,
          "sha512": "b508f5c4fa4e9df4140e1a4b166620e299757e0a4df2468b946003285e0e34162a2c8fe8f93f3563822b871fabd0f8b278ef09af92fbda1b1f768b9a20cb801f",
          "sha256": "98316dddc3ca7e20af0259992bb2d964cbad8fd4c13dc317c93532a58bd9b215",
          "sha1": "e0d468f80b3a170b0240256469c8c5e0f242a4c1",
          "md5": "ea8aef85263770256b0d42cc8ebb618e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-transformer",
          "version": {
            "requires": "5.2.9999"
          }
        },
        {
          "group": "dev.architectury",
          "module": "tiny-remapper",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "architectury-plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin-3.4-SNAPSHOT.jar",
          "size": 121817,
          "sha512": "b508f5c4fa4e9df4140e1a4b166620e299757e0a4df2468b946003285e0e34162a2c8fe8f93f3563822b871fabd0f8b278ef09af92fbda1b1f768b9a20cb801f",
          "sha256": "98316dddc3ca7e20af0259992bb2d964cbad8fd4c13dc317c93532a58bd9b215",
          "sha1": "e0d468f80b3a170b0240256469c8c5e0f242a4c1",
          "md5": "ea8aef85263770256b0d42cc8ebb618e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "architectury-plugin-3.4-SNAPSHOT-sources.jar",
          "url": "architectury-plugin-3.4-SNAPSHOT-sources.jar",
          "size": 11528,
          "sha512": "7d486e84f2271ab9988f59cfa9c2eda7f5a40da8ed2e3301dba0ea2f0212d0e9a0a865674770164fc6b569ca0f5a19e98228dbfad15d68359a292090793b5c80",
          "sha256": "82f47a4f1e5d67a443ab8dc067f76260af3464535f1fb72e0bbafa6dcbd6ec98",
          "sha1": "f2c1ec0f56eac6fe731ec51068c08322dc77a33d",
          "md5": "62bcdb40bfc4bd5f1472257b9a725992"
        }
      ]
    }
  ]
}
