{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-setup",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-setup-1.0-SNAPSHOT.jar",
          "url": "mod-setup-1.0-SNAPSHOT.jar",
          "size": 1607168,
          "sha512": "97245733666253fab5f13e8b807d3aa0fcf65f250500c32719bbab20501f14f1fd620d8f7eba1df029838576dae8f82d3f3a56e69e1c61dd2ef6c7ff6c57d0ba",
          "sha256": "fd018dac26ce984e4ea129a80aa422b0b2402a66fa9dbdf030685c7f885df814",
          "sha1": "5f50b9e56d32b76e827574d0a992620bd3daf594",
          "md5": "f2bef3bb5ab71e5c735f00e29ecc6b28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.fastmc",
          "module": "multi-jdk",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "requires": "5.1.58"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixingradle",
          "version": {
            "requires": "0.7-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mod-setup-1.0-SNAPSHOT.jar",
          "url": "mod-setup-1.0-SNAPSHOT.jar",
          "size": 1607168,
          "sha512": "97245733666253fab5f13e8b807d3aa0fcf65f250500c32719bbab20501f14f1fd620d8f7eba1df029838576dae8f82d3f3a56e69e1c61dd2ef6c7ff6c57d0ba",
          "sha256": "fd018dac26ce984e4ea129a80aa422b0b2402a66fa9dbdf030685c7f885df814",
          "sha1": "5f50b9e56d32b76e827574d0a992620bd3daf594",
          "md5": "f2bef3bb5ab71e5c735f00e29ecc6b28"
        }
      ]
    }
  ]
}
