{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "ow2-asm-ktdsl",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "ow2-asm-ktdsl-1.0-SNAPSHOT.jar",
          "url": "ow2-asm-ktdsl-1.0-SNAPSHOT.jar",
          "size": 8782,
          "sha512": "6538ae27544e63f938737f4c8b115650afe64593858ce017a06fafec199c74e75112f8e51623b6b5bef982dd58006e0436b2a230b908b5020612f239d18d43e9",
          "sha256": "c9a5960c5ff8dcca5b4ffab034f08319855241665c4462dcbedf297e2cc44a22",
          "sha1": "cb6048fc15a48d94d52b58006e95f9455c251ba2",
          "md5": "b4bd8dadbca75c486b578c9e1458b448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "ow2-asm-ktdsl-1.0-SNAPSHOT.jar",
          "url": "ow2-asm-ktdsl-1.0-SNAPSHOT.jar",
          "size": 8782,
          "sha512": "6538ae27544e63f938737f4c8b115650afe64593858ce017a06fafec199c74e75112f8e51623b6b5bef982dd58006e0436b2a230b908b5020612f239d18d43e9",
          "sha256": "c9a5960c5ff8dcca5b4ffab034f08319855241665c4462dcbedf297e2cc44a22",
          "sha1": "cb6048fc15a48d94d52b58006e95f9455c251ba2",
          "md5": "b4bd8dadbca75c486b578c9e1458b448"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ow2-asm-ktdsl-1.0-SNAPSHOT-sources.jar",
          "url": "ow2-asm-ktdsl-1.0-SNAPSHOT-sources.jar",
          "size": 1651,
          "sha512": "1c6da89897124d3e74b57dce0d1c0a67e29fb79dd2d62fe9409981680279a00c873b587a462c92d186e8c1304388ffc817bb1999ccf6a48f6bf5a69546ef4dce",
          "sha256": "3a945e0b406b435aeda248e37bcffda03d22be42e09e0f620f9dfce58cea0aae",
          "sha1": "3e14bb0db09b68b64891fb036f5ffa9fb9244506",
          "md5": "0d41a3f906269d0f30774e80aa7f809d"
        }
      ]
    }
  ]
}
