{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "fastmc-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElementsJava8",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.0-SNAPSHOT-java8.jar",
          "url": "fastmc-common-1.0-SNAPSHOT-java8.jar",
          "size": 120223,
          "sha512": "34cde815f74d2de459c3cff3cb121955899a94e71846a44f63f8cf8b715c5903fb5a23610223fc5fa79366226af5928504f1d1a1675136989f48387154976a3a",
          "sha256": "eb7c9938a54c724bd744354cae62d2774bc14bd1917338ca350b126cd435fbfc",
          "sha1": "8b0ddbb4e298e48e8c9a8a10c286c97fad1c688c",
          "md5": "6c59089a97c00b2bf4429a4ce23b2e63"
        }
      ]
    },
    {
      "name": "runtimeElementsJava8",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.0-SNAPSHOT-java8.jar",
          "url": "fastmc-common-1.0-SNAPSHOT-java8.jar",
          "size": 120223,
          "sha512": "34cde815f74d2de459c3cff3cb121955899a94e71846a44f63f8cf8b715c5903fb5a23610223fc5fa79366226af5928504f1d1a1675136989f48387154976a3a",
          "sha256": "eb7c9938a54c724bd744354cae62d2774bc14bd1917338ca350b126cd435fbfc",
          "sha1": "8b0ddbb4e298e48e8c9a8a10c286c97fad1c688c",
          "md5": "6c59089a97c00b2bf4429a4ce23b2e63"
        }
      ]
    },
    {
      "name": "apiElementsJava17",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.0-SNAPSHOT-java17.jar",
          "url": "fastmc-common-1.0-SNAPSHOT-java17.jar",
          "size": 120675,
          "sha512": "64e6b2cd88bc2f1dfd33b16d45093efbd3afe3380f432b9b81867b912a05ffa82e0aa7318e1bd97d0344522b45d82feab27f08b266a6a0fb8b235abaea7ab421",
          "sha256": "5f32b85e9fdac515b26eafc8c4cd50525404c74f3eb9d7260b71f16ab07b8dcc",
          "sha1": "083d915b784a31f39e215985316f610cf2d7d36c",
          "md5": "9b0bb3e1374b52bddc1c92e2e128f2a1"
        }
      ]
    },
    {
      "name": "runtimeElementsJava17",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fastmc-common-1.0-SNAPSHOT-java17.jar",
          "url": "fastmc-common-1.0-SNAPSHOT-java17.jar",
          "size": 120675,
          "sha512": "64e6b2cd88bc2f1dfd33b16d45093efbd3afe3380f432b9b81867b912a05ffa82e0aa7318e1bd97d0344522b45d82feab27f08b266a6a0fb8b235abaea7ab421",
          "sha256": "5f32b85e9fdac515b26eafc8c4cd50525404c74f3eb9d7260b71f16ab07b8dcc",
          "sha1": "083d915b784a31f39e215985316f610cf2d7d36c",
          "md5": "9b0bb3e1374b52bddc1c92e2e128f2a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastmc-common-1.0-SNAPSHOT-sources.jar",
          "url": "fastmc-common-1.0-SNAPSHOT-sources.jar",
          "size": 26355,
          "sha512": "36c3ab1f09d6540691b0aea3c47dfc8aaaeef831ef7e899e630841d04061d2543ed78b9d9603f07a19622e14ba608f8480cb75a04549657f3b55f6e8af97eb3d",
          "sha256": "6b72535f49ab2361067305dd14157a110d2e3d115943ed29295056b56b651d93",
          "sha1": "3f42cfaf1d4369ea67dfd06e3cd5886030559fcb",
          "md5": "6ca9f7ce5d5ba2c037531a9a4ebe486a"
        }
      ]
    }
  ]
}
