{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-setup",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-setup-1.1-SNAPSHOT.jar",
          "url": "mod-setup-1.1-SNAPSHOT.jar",
          "size": 2020061,
          "sha512": "6c16e9d604fcd58b8a5e6a1bfd9397820d85892602caf30811bd377c044afdd1ff4d103c30dae922b52dea5c918c7aac4be132ba2e112273580b21de7f216652",
          "sha256": "62b939f7cec1707ae743fc7f4f8937311f6746468d467df29cb5e8a2bdc47314",
          "sha1": "27b1ee76ce91500986d4afba0b0c06b0808efae0",
          "md5": "6f09f43dd8c6afee83d4981f9d1cdb07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "jar-optimizer",
          "version": {
            "requires": "1.2-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "multi-jdk",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "fast-remapper",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "mod-loader-plugin",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "requires": "5.1.58"
          }
        }
      ],
      "files": [
        {
          "name": "mod-setup-1.1-SNAPSHOT.jar",
          "url": "mod-setup-1.1-SNAPSHOT.jar",
          "size": 2020061,
          "sha512": "6c16e9d604fcd58b8a5e6a1bfd9397820d85892602caf30811bd377c044afdd1ff4d103c30dae922b52dea5c918c7aac4be132ba2e112273580b21de7f216652",
          "sha256": "62b939f7cec1707ae743fc7f4f8937311f6746468d467df29cb5e8a2bdc47314",
          "sha1": "27b1ee76ce91500986d4afba0b0c06b0808efae0",
          "md5": "6f09f43dd8c6afee83d4981f9d1cdb07"
        }
      ]
    }
  ]
}
