{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fastmc",
    "module": "mod-setup",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-setup-1.1-SNAPSHOT.jar",
          "url": "mod-setup-1.1-SNAPSHOT.jar",
          "size": 2018841,
          "sha512": "78a33904078385c416a011fa6e3441a6a7c2b20ccc0267b4453f88686c41517262de6d77cb68fdcdbf4329f61fb464465fac4e0cfea4b2c73be7087c2fc64fcd",
          "sha256": "b74647988d2edda4919d41e44da052162ea473d96c8445bd21be1bc23ebb9b92",
          "sha1": "3d529cfc6e83da99d978d49224262b1f8aea82fb",
          "md5": "281044b73571c41a84fff0d1e02c53a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "dev.luna5ama",
          "module": "jar-optimizer",
          "version": {
            "requires": "1.2-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "multi-jdk",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "fast-remapper",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.fastmc",
          "module": "mod-loader-plugin",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "ForgeGradle",
          "version": {
            "requires": "5.1.58"
          }
        }
      ],
      "files": [
        {
          "name": "mod-setup-1.1-SNAPSHOT.jar",
          "url": "mod-setup-1.1-SNAPSHOT.jar",
          "size": 2018841,
          "sha512": "78a33904078385c416a011fa6e3441a6a7c2b20ccc0267b4453f88686c41517262de6d77cb68fdcdbf4329f61fb464465fac4e0cfea4b2c73be7087c2fc64fcd",
          "sha256": "b74647988d2edda4919d41e44da052162ea473d96c8445bd21be1bc23ebb9b92",
          "sha1": "3d529cfc6e83da99d978d49224262b1f8aea82fb",
          "md5": "281044b73571c41a84fff0d1e02c53a9"
        }
      ]
    }
  ]
}
