{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luna5ama",
    "module": "jar-optimizer",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-optimizer-1.2-SNAPSHOT.jar",
          "url": "jar-optimizer-1.2-SNAPSHOT.jar",
          "size": 60396,
          "sha512": "f307269a9e5236337c910e8ced5562c902db1ab614be76ce5af26c2b7b8cf32504f64212a5f687736c3d2470b3222f07ec4c07ffe913536c5a2738bef52c7cb3",
          "sha256": "15000106f44febc924f2e238a2e95b9275250e8b08f96bee7366df51ab3ac669",
          "sha1": "d3939dda576e011fd1fdc61c1f64d036e33bf10a",
          "md5": "a4e7fab16772a6fd73c516e5dfdc8d07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.11"
          }
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "jar-optimizer-1.2-SNAPSHOT.jar",
          "url": "jar-optimizer-1.2-SNAPSHOT.jar",
          "size": 60396,
          "sha512": "f307269a9e5236337c910e8ced5562c902db1ab614be76ce5af26c2b7b8cf32504f64212a5f687736c3d2470b3222f07ec4c07ffe913536c5a2738bef52c7cb3",
          "sha256": "15000106f44febc924f2e238a2e95b9275250e8b08f96bee7366df51ab3ac669",
          "sha1": "d3939dda576e011fd1fdc61c1f64d036e33bf10a",
          "md5": "a4e7fab16772a6fd73c516e5dfdc8d07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-optimizer-1.2-SNAPSHOT-sources.jar",
          "url": "jar-optimizer-1.2-SNAPSHOT-sources.jar",
          "size": 4448,
          "sha512": "7060d89e986132e459a5128d37efb19a1eb2da8b0e3a57ad9962831e80e6e067144d896a0bf3b57b7a21d9654290b34f4ef2f3466725c1026c38bc0c12d9684c",
          "sha256": "986189081e12e7c78c79df6de334f2dd3b21edf6b9bd697c359077274c5da064",
          "sha1": "8da1480424966a0c550955545c3f12cf6e7a14e6",
          "md5": "1d448e43aeed2e0153e5ccc3a73371bb"
        },
        {
          "name": "jar-optimizer-1.2-SNAPSHOT-sources.jar",
          "url": "jar-optimizer-1.2-SNAPSHOT-sources.jar",
          "size": 4448,
          "sha512": "7060d89e986132e459a5128d37efb19a1eb2da8b0e3a57ad9962831e80e6e067144d896a0bf3b57b7a21d9654290b34f4ef2f3466725c1026c38bc0c12d9684c",
          "sha256": "986189081e12e7c78c79df6de334f2dd3b21edf6b9bd697c359077274c5da064",
          "sha1": "8da1480424966a0c550955545c3f12cf6e7a14e6",
          "md5": "1d448e43aeed2e0153e5ccc3a73371bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-optimizer-1.2-SNAPSHOT-javadoc.jar",
          "url": "jar-optimizer-1.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "78a1c0664b9b49ab3a30f22f7b25ad9e1f5c69f98685f8a79e6e5266e38d87656fc3134326d1be38d169df49b3cb4c625089b2f6d24670b0fb503963d9826d30",
          "sha256": "afa7cc56f5b8b4940ffdf6b0b9aca8131066376e0e1e5610c6ad69f8cc81d14d",
          "sha1": "26aeaf7b9ec316ec3bf6a4079fc845965deb2c30",
          "md5": "8576ae9b5b50de5ef72ac9eb76b99553"
        }
      ]
    }
  ]
}
