name: MavenPublish

on:
    workflow_call:
        inputs:
            target-owner:
                required: true
                type: string
            target-repo:
                required: true
                type: string
            target-branch:
                required: true
                type: string
        secrets:
            token:
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout previous maven repo
                run: |
                    cd ~
                    git clone https://github.com/${{ inputs.target-owner }}/${{ inputs.target-repo }}.git
                    cd ~/${{ inputs.target-repo }}
                    git fetch
                    git switch ${{ inputs.target-branch }}
                    echo mvn_temp=$(pwd) >> $GITHUB_ENV

            -   name: Checkout current
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.token }}

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 17

            -   uses: burrunan/gradle-cache-action@v1
                name: Gradle publish to temp
                env:
                    mvn_temp: ${{ env.mvn_temp }}
                with:
                    arguments: --build-cache publishAllPublicationsToTempRepository

            -   name: Commit and push
                run: |
                    cd ${{ env.mvn_temp }}
                    git pull
                    git add .
                    git config user.name "GitHub Actions Bot"
                    git config user.email "<>"
                    git commit -a -m "Updated $(cat $GITHUB_WORKSPACE/build/tmp/maven-repo/version_info.txt)"
                    git push https://${{ secrets.token }}:${{ secrets.token }}@github.com/${{ inputs.target-owner }}/${{ inputs.target-repo }}.git ${{ inputs.target-branch }}
